hopshadoop/hops-metadata-dal-impl-ndb

- src/main/resources/ndb-config.properties
- src/main/resources/ndb-config.properties~
This pull request adds the ndb configuration file that somehow got lost during the initial push.
> Add missing configuration file

- schema/schema.sql
Correcting sql schema to resolve foreign key errors due to different charsets
> fixe sql schema

- pom.xml
- schema/schema.sql
- src/main/java/io/hops/metadata/ndb/DBSessionProvider.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
- src/main/resources/ndb-config.properties
Fixed Performance Issures with dir listing
> Fixed Performance Issures with dir listing

- schema/schema.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/BlockInfoClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ReplicaClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ReplicaUnderConstructionClusterj.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/MySQLQueryHelper.java
get replicas block ids using SQL instead of clusterj
> remove replica_index from replicas and replica_under_construction tables

- schema/schema.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/AppSchedulingInfoClusterJ.java
Add columns to yarn_appschedulinginfo in order to display application status in the user interface.
> Add column for hopsworks

- src/main/java/io/hops/metadata/ndb/mysqlserver/MySQLQueryHelper.java
> Fix min/max mixup

- schema/schema.sql
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/ResourceRequestOfContainerClusterJ.java
https://issues.apache.org/jira/secure/attachment/12655718/Yarn-1408.11.patch
> YARN-1408 with resourceRequest recovered

- schema/schema.sql
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/ContainersCheckPointsClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/ContainersLogsClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/YarnHistoryPriceClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/YarnProjectsDailyCostClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/YarnProjectsQuotaClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/YarnRunningPriceClusterJ.java
- src/main/native/streaming/resources/RT_EventAPIConfig.ini
Add mechanism to persist informations relative to the uber pricing system.
Preparation for: hopshadoop/hops#257
> Price fixer

- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/FullRMNodeClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/rmstatestore/SecretMamagerKeysClusterJ.java
- src/main/native/streaming/resources/RT_EventAPIConfig.ini
- src/test/java/io/hops/metadata/ndb/dalimpl/yarn/TestFullRMNodeClusterJ.java
preparation for hopshadoop/hops #259
> Distribut token management

- src/main/native/streaming/include/HopsReturnObject.h
- src/main/native/streaming/include/HopsSimulationReturnObject.h
- src/main/native/streaming/resources/RT_EventAPIConfig.ini
- src/main/native/streaming/src/HopsJNICallBackObject.cpp
- src/main/native/streaming/src/HopsReturnObject.cpp
correct bug with the streaming library not accepting float
Linked to hopshadoop/hops#262
> Rizvi stream float

- src/main/native/streaming/src/HopsConfigReader.cpp
Correct a bug appearing with the new String management in gcc5
> Gcc 5 correction

- schema/schema.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/GroupClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/UserClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/UserGroupClusterj.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/MySQLQueryHelper.java
- src/main/resources/ndb-config.properties
Use autoincrement integer as an id for Users and groups
> Don't read users/groups names while reading the inodes

- schema/schema.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/MetadataLogClusterj.java
Use timestamps instead of logicaltime
> Added INode ParentId and Name to hdfs_metadata_log

- schema/schema.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/LeasePathClusterj.java
added last_block_id and penultimate_block_id to leasepath
> Fixes HOPS-17

- src/main/java/io/hops/metadata/ndb/mysqlserver/HopsSQLExceptionHelper.java
check for transient sql exceptions
> Fixes HOPS-25

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/BlockChecksumClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/BlockInfoClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/BlockLookUpClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/CorruptReplicaClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/EncodingJobsClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/EncodingStatusClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ExcessReplicaClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/GroupClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeAttributesClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/InvalidatedBlockClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/LeaseClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/LeasePathClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/MetadataLogClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/MisReplicatedRangeQueueClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/OnGoingSubTreeOpsClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/PendingBlockClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/QuotaUpdateClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/RepairJobsClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ReplicaClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ReplicaUnderConstructionClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/SafeBlocksClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/StorageIdMapClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/UnderReplicatedBlockClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/UserClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/UserGroupClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/VariableClusterj.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-29?filter=allopenissues
> HOPS-29: make sure to release dto objects in finally block

- schema/schema.sql
> Fixes HOPS-44

- schema/schema.sql
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/JniNdbEventStreaming.java
- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/UserClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/ContainerToDecreaseClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/ContainerToSignalClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/FullRMNodeClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/RMNodeApplicationsClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/ReservationStateClusterJ.java
- src/main/native/streaming/include/ContainerToDecreaseTableTailer.h
- src/main/native/streaming/include/ContainerToSignalTableTailer.h
- src/main/native/streaming/include/JniNdbEventStreamingImp.h
- src/main/native/streaming/src/ContainerToDecreaseTableTailer.cpp
- src/main/native/streaming/src/ContainerToSignalTableTailer.cpp
- src/main/native/streaming/src/JniNdbEventStreamingImp.cpp
- src/test/java/io/hops/metadata/ndb/dalimpl/yarn/TestFullRMNodeClusterJ.java
https://hopshadoop.atlassian.net/browse/HOPS-65
> [HOPS-65] update to follow hadoop 2.8.2 updates

- schema/schema.sql
https://hopshadoop.atlassian.net/browse/HOPS-85
> [HOPS-85] Change collate for all the remaining yarn_* tables

- schema/schema.sql
- schema/update-schema_2.8.2.1_to_2.8.2.2.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/MetadataLogClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-97
> [HOPS-97] Use logical time per inode instead of timestamp for ordering

- pom.xml
- src/main/java/io/hops/metadata/ndb/JniNdbEventStreaming.java
- src/main/native/streaming/include/JniNdbEventStreamingImp.h
- src/main/native/streaming/include/RmNodeApplicationsTableTailer.h
- src/main/native/streaming/src/JniNdbEventStreamingImp.cpp
- src/main/native/streaming/src/RmNodeApplicationsTableTailer.cpp
need hopshadoop/hops-metadata-dal#95
https://hopshadoop.atlassian.net/browse/HOPS-127
https://hopshadoop.atlassian.net/browse/HOPS-128
> [Hops-128] and [Hops-127]

- schema/schema.sql
- schema/update-schema_2.8.2.2_to_2.8.2.3.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/quota/ProjectsDailyCostClusterJ.java
https://hopshadoop.atlassian.net/browse/HOPS-149
Depends on hopshadoop/hops-metadata-dal#96
> [HOPS-149] add application IDs in project daily cost

- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/rmstatestore/ApplicationStateClusterJ.java
https://hopshadoop.atlassian.net/browse/HOPS-157
Corresponding Hops tests: https://bbc1.sics.se/jenkins/view/pull/job/hops-pull/35/
> [HOPS-157] Check that the application name is not null and too long before to truncate.

- .github/pull_request_template.md
https://hopshadoop.atlassian.net/browse/HOPS-159
> [HOPS-159] Add PR template

- schema/schema.sql
- schema/update-schema_2.8.2.3_to_2.8.2.4.sql
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/BlockInfoClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/CorruptReplicaClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ExcessReplicaClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/InvalidatedBlockClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ReplicaUnderConstructionClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/StoragesClusterj.java
- src/main/resources/ndb-config.properties.template
https://hopshadoop.atlassian.net/browse/HOPS-86
New feature
Work done mostly by bcleenders, implementing necessary database suport to port the following HDFS jiras and all the corresponding sub jiras to hops:
- HDFS-2832
- HDFS-5682
- HDFS-6702
No
hopshadoop/hops-metadata-dal#99
hopshadoop/hops#429
> [HOPS-86] Heterogeneous storage

- schema/schema.sql
https://hopshadoop.atlassian.net/browse/HOPS-164
improvement 
we can use flyway to update the schema
no
> [HOPS-164] Schema fixes for flyway

- schema/create-tables.sh
- schema/schema.sql
https://hopshadoop.atlassian.net/browse/HOPS-165
improvement
add a script to setup the tables in the database.
> [HOPS-165]

- schema/schema.sql
https://hopshadoop.atlassian.net/browse/HOPS-166
Bug fix
> [HOPS-166] Alter table storage type to 'ndb' for flyway

- schema/create-tables.sh
https://hopshadoop.atlassian.net/browse/HOPS-168
Bug fix
No
> [HOPS-168]

- schema/update-schema_2.8.2.3_to_2.8.2.4.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/OnGoingSubTreeOpsClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ReplicaUnderConstructionClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-197
Require hopshadoop/hops-metadata-dal#102
> [HOPS-197] apply HDFS-4721

- schema/update-schema_2.8.2.3_to_2.8.2.4.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-246
Need hopshadoop/hops-metadata-dal#104
> [HOPS-246] apply HDFS-4772

- LICENSE_OF_DEPENDENCIES.md
https://hopshadoop.atlassian.net/browse/HOPS-264
> [HOPS-264] add LICENSE_OF_DEPENDENCIES.md

- schema/update-schema_2.8.2.3_to_2.8.2.4.sql
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/RetryCacheEntryClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-281
Depends on hopshadoop/hops-metadata-dal#106
> [HOPS-281] apply HDFS-5025

- pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-320
> [HOPS-320] update ndb version to 7.5.9

- schema/update-schema_2.8.2.3_to_2.8.2.4.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/PendingBlockClusterj.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/MySQLQueryHelper.java
https://hopshadoop.atlassian.net/browse/HOPS-305
Depends on hopshadoop/hops-metadata-dal#107
> [HOPS-305] apply HDFS-5020

- schema/schema.sql
- schema/update-schema_2.8.2.3_to_2.8.2.4.sql
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/AceClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-5
Feature: Adding extended acls to HopsFS
See design document: "Hops ACLs" and eventually readthedocs in the ACLs section
> [HOPS-5] Hops ACLs.

- pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-350
> [HOPS-350] Update ClusterJ to 7.5.10

- pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-351
> [HOPS-351] added profiles to enable building on Mac and Linux machines

- schema/update-schema_2.8.2.3_to_2.8.2.4.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/CorruptReplicaClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ReplicaUnderConstructionClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-399
Need hopshadoop/hops-metadata-dal#112
> [HOPS-399] apply HDFS-5438

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
[Hops-458] SubTree operation on a large directory with millions of immediate children can kill the database.
https://hopshadoop.atlassian.net/browse/HOPS-458
Bug fix
Nay
None
> [HOPS-458] SubTree operation on a large directory with millions of immediate children can kill the database.

- pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-475
> [HOPS-475] update clusterj to 7.6.6

- schema/create-tables.sh
https://hopshadoop.atlassian.net/browse/HOPS-485
> [HOPS-485] add 2.8.2.5 to create-tables

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/BlockInfoClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-480
Need hopshadoop/hops-metadata-dal#116
> [HOPS-480] replace full table scan by primary key operation

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/OnGoingSubTreeOpsClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-477
bug fix 
> [HOPS-477] Added GC for STO locks left by dead namenodes

- pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-570
dependency update
> [HOPS-570] update NDB to 7.6.7

- NDB/upgrade-ndb.sh
https://hopshadoop.atlassian.net/browse/HOPS-572
Bug fix 
Script to upgrade clusterj to new versions of NDB was broken.
> HOPS-572 fix script to deploy new versions of clusterj

- NDB/upgrade-ndb.sh
- pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-571
Bug fix
> [HOPS-571] use bbc1 repo instead of kompics

- schema/update-schema_2.8.2.4_to_2.8.2.5.sql
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/CacheDirectiveClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/CacheDirectivePathClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/CachePoolClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/CachedBlockClusterJ.java
https://hopshadoop.atlassian.net/browse/HOPS-598
> [HOPS-598] apply HDFS-4949

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/EncodingStatusClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-625
Bug fix
Block are removed in batch instead of one by one
Depends on hopshadoop/hops-metadata-dal#124
> [HOPS-625] batch blocks removal

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/BlockLookUpClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-628
performance fix
improve replicas removal efficiency.
Depends on hopshadoop/hops-metadata-dal#125
> [HOPS-628] make the replicas removal more efficient.

- schema/update-schema_2.8.2.4_to_2.8.2.5.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/CorruptReplicaClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/MisReplicatedRangeQueueClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-632
depends on hopshadoop/hops-metadata-dal#126
> [HOPS-632] apply HDFS-5535

- src/main/java/io/hops/metadata/ndb/DBSessionProvider.java
https://hopshadoop.atlassian.net/browse/HOPS-508
Bug fix
> [HOPS-508] set lock mode back to read_committed when returning a session

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ExcessReplicaClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-654
Bug fix
Depends on hopshadoop/hops-metadata-dal#130
> [HOPS-654] get excess replica metric from DB

- schema/create-tables.sh
- schema/update-schema_2.8.2.5_to_2.8.2.6.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/AceClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/BlockChecksumClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/BlockInfoClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/BlockLookUpClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/CachedBlockClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/CorruptReplicaClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/EncodingStatusClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ExcessReplicaClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeAttributesClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/InMemoryFileInodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/InvalidatedBlockClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/LargeOnDiskFileInodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/MediumOnDiskFileInodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/MetadataLogClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/PendingBlockClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/QuotaUpdateClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ReplicaClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ReplicaUnderConstructionClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/SmallOnDiskFileInodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/UnderReplicatedBlockClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-644
bug fix
change inodeId from int to long
depends on hopshadoop/hops-metadata-dal#131
> [HOPS-644] change inodeID from int to long

- schema/update-schema_2.8.2.4_to_2.8.2.5.sql
- schema/update-schema_2.8.2.5_to_2.8.2.6.sql
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ActiveBlockReportsClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-482
bug fix
depends on hopshadoop/hops-metadata-dal#132
> [HOPS-482] Block report load balancing

- src/main/java/io/hops/metadata/ndb/mysqlserver/HopsSQLExceptionHelper.java
- src/main/java/io/hops/metadata/ndb/wrapper/HopsExceptionHelper.java
https://hopshadoop.atlassian.net/browse/HOPS-690
https://hopshadoop.atlassian.net/browse/HOPS-691
> [HOPS-690] and [HOPS-691]

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/UserGroupClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-676
> [HOPS-676] Rewrite the UsersGroups cache

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/UnderReplicatedBlockClusterj.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-749
bug fix
> [HOPS-749] make UnderReplicatedBlockClusterj.removeAll() scalable.

- schema/update-schema_2.8.2.5_to_2.8.2.6.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-756
Depends on hopshadoop/hops-metadata-dal#135
> [HOPS-756] apply HDFS-6583

- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/MysqlServerConnector.java
https://hopshadoop.atlassian.net/browse/HOPS-814
require hopshadoop/hops-metadata-dal#139
> [HOPS-814] return session after LightWeightRequestHandler

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/MySQLQueryHelper.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-806
> [HOPS-806] get max inode id

- schema/create-tables.sh
- schema/update-schema_2.8.2.6_to_2.8.2.7.sql
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-848
require hopshadoop/hops-metadata-dal#143
> [HOPS-848] apply HDFS-6783

- pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-863
> [HOPS-863] Upgrade ClusterJ to 7.6.8

- schema/update-schema_2.8.2.6_to_2.8.2.7.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/UnderReplicatedBlockClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-958
Depends on hops-metadata-dal#146
> [HOPS-958] apply HDFS-7165

- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
https://hopshadoop.atlassian.net/browse/HOPS-1010
update
improved logging
no
No need to run tests just merge it. All of the three projects have been updated
> [HOPS-1010] Removing useless logs that are printed at INFO loggin level

- pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-1047
> [HOPS-1047] update ndb to 7.6.9

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ActiveBlockReportsClusterj.java
* https://hopshadoop.atlassian.net/browse/HOPS-1100
Depends on  hopshadoop/hops-metadata-dal#151
> [HOPS-1100] BRTrackingService.assignWork in one transaction.

- schema/update-schema_2.8.2.7_to_2.8.2.8.sql
https://hopshadoop.atlassian.net/browse/HOPS-1151
> [HOPS-1151] Reading all replicas for a bucket is a FTS.

- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1121?filter=myopenissues
> [HOPS-1121] Remove DB connect information from the exception

- schema/update-schema_2.8.2.7_to_2.8.2.8.sql
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1113?filter=myopenissues
improved performance
> [HOPS-1113] FTIS on Inodes table during inverse path look

- schema/update-schema_2.8.2.7_to_2.8.2.8.sql
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/BlockInfoClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/DirectoryWithQuotaFeatureClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/QuotaUpdateClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-1146
https://hopshadoop.atlassian.net/browse/HOPS-1158
depends on hopshadoop/hops-metadata-dal#154
> [HOPS-1146] and [HOPS-1158]

- schema/update-schema_2.8.2.7_to_2.8.2.8.sql
https://hopshadoop.atlassian.net/browse/HOPS-1207
Bug fix
> [HOPS-1207] Change type of application and attempt state in db

- schema/update-schema_2.8.2.7_to_2.8.2.8.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/DirectoryWithQuotaFeatureClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/QuotaUpdateClusterj.java
> [HOPS-1168] HDFS-7775

- schema/update-schema_2.8.2.7_to_2.8.2.8.sql
Revert HOPS-1113 because it has unexpected side effects.
> REVERT HOPS-1113

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1152?filter=allopenissues
hops layer also changed
https://github.com/hopshadoop/hops/pull/639
https://github.com/hopshadoop/hops-metadata-dal/pull/155
https://github.com/hopshadoop/hops-metadata-dal-impl-ndb/pull/193
> [HOPS-1152] Allow disabling Users/Groups Cache on the NN side

- schema/update-schema_2.8.2.7_to_2.8.2.8.sql
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/MetadataLogClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/XAttrClusterJ.java
https://hopshadoop.atlassian.net/browse/HOPS-1312
feature
The same behaviour as HDFS, except the limits for name and value are different. The name size can be up to 255 characters while the value size is up to 13730 characters.
https://hadoop.apache.org/docs/r2.5.2/hadoop-project-dist/hadoop-hdfs/ExtendedAttributes.html
> [HOPS-1312] Support extended attributes per file based on HDFS-2006

- schema/update-schema_2.8.2.7_to_2.8.2.8.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/rmstatestore/ApplicationAttemptStateClusterJ.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1216
Bug fix
depends on hopshadoop/hops-metadata-dal#160
> [HOPS-1216] fix Tupple does not exist when deleting application attempts

- schema/update-schema_2.8.2.7_to_2.8.2.8.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/DirectoryWithQuotaFeatureClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/QuotaUpdateClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-1215?filter=-1
> [HOPS-1215] Set storage type for Small Files stored in the database

- schema/update-schema_2.8.2.7_to_2.8.2.8.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ActiveBlockReportsClusterj.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1214
> [HOPS-1214] Blockreport load balancing per NN

- src/main/java/io/hops/metadata/ndb/wrapper/HopsExceptionHelper.java
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1313
> [HOPS-1313] Suppress transient exceptions

- NDB/upgrade-ndb.sh
- pom.xml
- schema/update-schema_2.8.2.7_to_2.8.2.8.sql
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1332?filter=allopenissues
> [HOPS-1332] Ugrade to NDB 7.6.10

- NDB/clusterj-fixes/clusterj-fix.patch
https://hopshadoop.atlassian.net/browse/HOPS-1337
Bug fix
> [HOPS-1337] fix nullpointer in clusterJ

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/InMemoryFileInodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/LargeOnDiskFileInodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/MediumOnDiskFileInodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/SmallOnDiskFileInodeClusterj.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/MySQLQueryHelper.java
https://hopshadoop.atlassian.net/browse/HOPS-1351
> [HOPS-1351] Making small files size reconfigurable

- pom.xml
- schema/create-tables.sh
- schema/update-schema_2.8.2.8_to_3.2.0.0.sql
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/dalimpl/configurationstore/ConfClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/configurationstore/ConfMutationClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/DirectoryWithQuotaFeatureClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/QuotaUpdateClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/rmstatestore/ApplicationAttemptStateClusterJ.java
- src/main/java/io/hops/metadata/ndb/wrapper/HopsExceptionHelper.java
- src/test/java/io/hops/metadata/ndb/dalimpl/yarn/TestFullRMNodeClusterJ.java
https://hopshadoop.atlassian.net/browse/HOPS-1378
Depends on hopshadoop/hops-metadata-dal#170
> [HOPS-1378] Move most of the codebase to hadoop 3.2.0

- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/quota/ProjectQuotaClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/quota/ProjectsDailyCostClusterJ.java
https://hopshadoop.atlassian.net/browse/HOPS-1385
depends on hopshadoop/hops-metadata-dal#171
> [HOPS-1385] redo the Yarn quota system for hadoop 3

- pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-1379
> [HOPS-1379] make support for hbase 2 compile and pass tests

- schema/update-schema_2.8.2.8_to_3.2.0.0.sql
https://hopshadoop.atlassian.net/browse/HOPS-1405
bug fix
> [HOPS-1405] Fix Var table

- pom.xml
https://hopshadoop.atlassian.net/browse/HOPS-1384
> [HOPS-1384] Put back check invariants for Hadoop-Client-Modules

- schema/create-tables.sh
- schema/update-schema_2.8.2.8_to_2.8.2.9.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/XAttrClusterJ.java
https://hopshadoop.atlassian.net/browse/HOPS-1434
https://hopshadoop.atlassian.net/browse/HOPS-1451
> [HOPS-1434][HOPS-1451]

- schema/update-schema_2.8.2.8_to_2.8.2.9.sql
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/EncryptionZoneClusterJ.java
Merge the following jiras:
- HDFS-6134 and HADOOP-10150 subtasks
- HDFS-6954
- HDFS-6905
- HDFS-6986
- HDFS Credential Provider related Unit Test Failure
- HDFS-6951
- HDFS-6966
- HDFS-7061
- HDFS-7032
- HDFS-7006
- HDFS-6851
- HDFS-6843
- HDFS-7004
- HDFS-7047
- HDFS-6970
- HDFS-7115
- HDFS-7126
- HDFS-7078
- HDFS-6987.
- HDFS-7139
- HDFS-7138.
- HDFS-7077
- HDFS-7124
- HDFS-7179
- HDFS-7181
- HDFS-7209
- HDFS-7190
- HDFS-7252
- HDFS-6824.
- HDFS-7243.
- HDFS-6938
- HDFS-7536
- HDFS-7530
- HDFS-7718
- HDFS-8004
- HADOOP-11312
https://hopshadoop.atlassian.net/browse/HOPS-1501
new feature: encryption …
> [HOPS-1501] add encryption at rest feature:

- src/main/java/io/hops/metadata/ndb/DBSessionProvider.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/BlockChecksumClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/EncodingStatusClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/QuotaUpdateClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/VariableClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/FullRMNodeClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/RMLoadClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/ResourceClusterJ.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/CountHelper.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/MySQLQueryHelper.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/MysqlServerConnector.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/ScriptRunner.java
https://hopshadoop.atlassian.net/browse/HOPS-1514
bug fix
> [HOPS-1514] Cleanup bad coding in metadata-dal-impl-ndb

- NDB/clusterj-fixes/clusterj-fix.patch
- pom.xml
https://hopshadoop.atlassian.net/projects/HOPS/issues/HOPS-1539?filter=allopenissues&orderby=created%20DESC
> [HOPS-1539] Bump NDB version 7.6.10 -> 7.6.12

- .gitignore
- README.md
- schema/update-schema_2.8.2.8_to_2.8.2.9.sql
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/FileProvXAttrBufferClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/FileProvenanceClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/AppProvenanceClusterJ.java
https://hopshadoop.atlassian.net/browse/HOPS-1541
feature - provenance
Log filesystem operations into a log tailed by epipe
This JIRA has changes to the database (add tables)
> [HOPS-1541] provenance

- pom.xml
> HOPSWORKS-1765 archiva

- NDB/clusterj-fixes/clusterj-fix.patch
- src/main/java/io/hops/metadata/ndb/DBSessionProvider.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
- src/main/java/io/hops/metadata/ndb/wrapper/HopsClusterJLogger.java
- src/main/java/io/hops/metadata/ndb/wrapper/HopsExceptionHelper.java
- src/main/java/io/hops/metadata/ndb/wrapper/HopsLoggerFactory.java
https://hopshadoop.atlassian.net/browse/HOPS-1553
> [HOPS-1553] Fixed ClusterJ logging

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ReplicaUnderConstructionClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-1564
> [HOPS-1564] Fixed bug in transaction cache

- schema/update-schema_2.8.2.9_to_2.8.2.10.sql
https://hopshadoop.atlassian.net/browse/HOPS-1566
> [HOPS-1566] Missing partition by for hdfs_file_provenance_xattrs_buffer

- schema/create-tables.sh
> fix create table for 3.2.0.0 after 2.8.2.10

- schema/update-schema_2.8.2.10_to_3.2.0.0.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/FileProvXAttrBufferClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/FileProvenanceClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/MetadataLogClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/XAttrClusterJ.java
https://hopshadoop.atlassian.net/browse/HOPS-1568
improvement
> [HOPS-1568] Add support for large XAttrs (>13500)

- schema/update-schema_2.8.2.10_to_3.2.0.0.sql
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/LeaseClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/LeaseCreationLocksClusterj.java
https://hopshadoop.atlassian.net/browse/HOPS-1573
https://hopshadoop.atlassian.net/browse/HOPS-1572
https://github.com/hopshadoop/hops-metadata-dal/pull/192
> [HOPS-1573] Fix garbage collection in Lease Paths

- schema/update-schema_2.8.2.10_to_3.2.0.0.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ReplicaUnderConstructionClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/RetryCacheEntryClusterj.java
> [HOPS-1571] Partition hdfs_retry_cache table

- schema/update-schema_2.8.2.10_to_3.2.0.0.sql
> [HOPS-1571] ADENDUM 2 the variable should be added if it is an update

- NDB/clusterj-fixes/clusterj-fix.patch
- NDB/upgrade-ndb.sh
- pom.xml
- src/main/java/io/hops/metadata/ndb/mysqlserver/HopsSQLExceptionHelper.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/MySQLQueryHelper.java
- src/main/resources/ndb-config.properties.template
> [HOPS-1581] Upgrade to NDB 8

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/BlockInfoClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ExcessReplicaClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/INodeClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/InvalidatedBlockClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ReplicaClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/ReplicaUnderConstructionClusterj.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/CountHelper.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/MySQLQueryHelper.java
depends on https://github.com/hopshadoop/hops-metadata-dal/pull/199
> add ee changes that should also have been made in community

- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
* HOPS-1623  https://hopshadoop.atlassian.net/browse/HOPS-1623
> [HOPS-1623] Reload schema on truncate

- src/main/java/io/hops/metadata/ndb/NdbStorageFactory.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/MysqlServerConnector.java
> [HOPSWORKS-CLOUD-1598] Added direct mem and DB utilization to HopsFS UI

- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/OnGoingSubTreeOpsClusterj.java
> [HOPSWORKS-CLOUD-1540] Fixing cleaning up subtree operations

- schema/create-tables.sh
> [HOPS-1626] Added missing schema files

- pom.xml
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/DBSessionProvider.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/LeaseCreationLocksClusterj.java
- src/main/java/io/hops/metadata/ndb/wrapper/HopsSession.java
- src/main/resources/ndb-config.properties.template
> [HOPS-1625] RonDB 21.04.0

- pom.xml
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/DBSessionProvider.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/LeaseCreationLocksClusterj.java
- src/main/java/io/hops/metadata/ndb/wrapper/HopsSession.java
- src/main/resources/ndb-config.properties.template
This reverts commit cbde54d639fbaf50631e0bb20e9abba9331d6020.
> Revert "[HOPS-1625] RonDB 21.04.0"

- pom.xml
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/DBSessionProvider.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/LeaseCreationLocksClusterj.java
- src/main/java/io/hops/metadata/ndb/wrapper/ClusterJCaching.java
- src/main/java/io/hops/metadata/ndb/wrapper/HopsSession.java
- src/main/java/io/hops/metadata/ndb/wrapper/HopsSessionFactory.java
- src/main/resources/ndb-config.properties.template
> [HOPS-1635] RonDB 21.04.0 and configurable ClusterJ caching

- schema/create-tables.sh
> [HOPS-1640] create schema files for 3.2.0.5

- src/main/java/io/hops/metadata/ndb/dalimpl/election/LeDescriptorClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/CorruptReplicaClusterj.java
- src/main/java/io/hops/metadata/ndb/dalimpl/yarn/quota/ProjectsDailyCostClusterJ.java
https://hopshadoop.atlassian.net/browse/HOPS-1647
Bug fix
Fix the order of entries in some primary key look ups.
> [HOPS-1647] fix primary key lookups

- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/DBSession.java
- src/main/java/io/hops/metadata/ndb/DBSessionProvider.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/MysqlServerConnector.java
- src/main/java/io/hops/metadata/ndb/wrapper/HopsSessionFactory.java
- src/main/resources/ndb-config.properties.template
> [HOPS-1654] Reconnect to NDB after network failure

- src/main/java/io/hops/metadata/ndb/mysqlserver/Constants.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/MysqlServerConnector.java
https://hopshadoop.atlassian.net/browse/HOPS-1656
New feature
Introduces a configuration property for Hikari (useSSL)
No
> [HOPS-1656] usessl configuration property for Hikari

- src/main/java/io/hops/metadata/ndb/mysqlserver/Constants.java
- src/main/java/io/hops/metadata/ndb/mysqlserver/MysqlServerConnector.java
- src/main/resources/ndb-config.properties.template
https://hopshadoop.atlassian.net/browse/HOPS-1656
> [HOPS-1656] MySQL usessl default value

- pom.xml
> [HOPS-1657] RonDB 21.04.2

- pom.xml
> [HOPSWORKS-3182] Bump RonDB version to 21.04.7

- pom.xml
> HOPSFS-18: Using RonDB 21.04.9

- schema/create-tables.sh
> HWORKS-192: Added schema update file

- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
> HOPSFS-27: Fixed log level for rollback operation

- pom.xml
https://hopsworks.atlassian.net/browse/HOPSFS-47
> [HOPSFS-47] Bump version to 3.2.0.9-SNAPSHOT

- pom.xml
> HOPSFS-52: Bumped RonDB to 21.04.10

- pom.xml
Reverts hopshadoop/hops-metadata-dal-impl-ndb#271
> Revert "HOPSFS-52: Bumped RonDB to 21.04.10"

- pom.xml
- src/main/java/io/hops/metadata/ndb/ClusterjConnector.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/AceClusterJ.java
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/XAttrClusterJ.java
- src/test/java/io/hops/metadata/ndb/dalimpl/hdfs/TestVariableTableUpgrade.java
> Hopsfs 57 se

- src/main/resources/ndb-config.properties.template
> HOPSFS-68: Disable ClusterJ DTO cache

- pom.xml
> HOPSFS-67: Bumpled RonDB version to 21.04.12

- dev-support/docker/Dockerfile
- pom.xml
- start-build-env.sh
> [HOPSFS-114] add a docker image to build and test

- pom.xml
> RONDB-394: Bump RonDB version to 21.04.14

- pom.xml
> RONDB-414: Final RonDB release 21.04.14

- pom.xml
> RONDB-458: Bump RonDB Version to 21.04.15

- pom.xml
HOPSFS-139 Bump Version to 22.10.1 Final
> HOPSFS-139 Bump Version to 22.10.1 Final

- dev-support/docker/Dockerfile
> HOPSFS-144: Fixed docker image. Installing jdk8 and maven togather fails

- pom.xml
RONDB-661 RonDB minor release 22.10.3
> RONDB-661 RonDB minor release 22.10.3

- pom.xml
HOPSFS-159: Release 3.2.0.13-RC0
> HOPSFS-159: Release 3.2.0.13-RC0

- pom.xml
- schema/create-tables.sh
HOPSFS-160: Release 3.2.0.14-SNAPSHOT
> HOPSFS-160: Release 3.2.0.14-SNAPSHOT

- schema/update-schema_3.2.0.12_to_3.2.0.13.sql
- src/main/java/io/hops/metadata/ndb/dalimpl/hdfs/RetryCacheEntryClusterj.java
> HOPSFS-162: Fixed Retry Cache Cleaner

- pom.xml
RONDB-693 RonDB minor release 22.10.5
> RONDB-693 RonDB minor release 22.10.5

- pom.xml
- schema/create-tables.sh
HOPSFS-178: Release 3.2.0.15-SNAPSHOT
> HOPSFS-178: Release 3.2.0.15-SNAPSHOT
